server:
  port: 8005

spring:
  application:
    name: cloud-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///E:/development/GitRepository/SpringCloudLearning/SharedConfigFiles/
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://eureka.register.at8003:8003/eureka/, http://eureka.register.at8004:8004/eureka/
      defaultZone: http://eureka.register.at8003:8003/eureka/
