server:
  port: 8004

eureka:
  instance:
    hostname: eureka.register.at8004
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka.register.at8003:8003/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
