server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloudlearning?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    initialization-mode: never
    continue-on-error: false
    #schema: classpath:schema-mysql.sql
    #data: classpath:data-mysql.sql
    druid:
      test-while-idle: true
      validation-query: select 1

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8003/eureka

mybatis:
  #mapper xml location
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.sheli.entities
