server:
  port: 8002

spring:
  application:
    name: cloud-ordering-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8003/eureka

crossmodule:
  payment:
    url: http://localhost:8001


