server:
  port: 8002

spring:
  application:
    name: cloud-ordering-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:8003/eureka
      defaultZone: http://eureka.register.at8003:8003/eureka/, http://eureka.register.at8004:8004/eureka/

crossmodule:
  payment:
    url: http://localhost:8001


